// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTaskApp.Infrastructure.Persistence;

#nullable disable

namespace MyTaskApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MyTaskAppDbContext))]
    [Migration("20261010132850_SkippedTables")]
    partial class SkippedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MyTaskApp.Domain.Agents.AgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Activity")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActivityChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HookTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TaskDevelopmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TaskDevelopmentId", "StartedAt");

                    b.HasIndex("TaskItemId", "StartedAt");

                    b.HasIndex(new[] { "TaskDevelopmentId" }, "IX_AgentSessions_TaskDevelopmentId_Active")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (1, 2)");

                    b.ToTable("AgentSessions", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Auditing.TaskAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Actor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TaskId", "OccurredAt");

                    b.ToTable("TaskAuditEntries", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Commands.CommandExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandLine")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DevelopmentCommandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorOutput")
                        .HasMaxLength(64000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KeepTerminalOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Output")
                        .HasMaxLength(64000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TagDirectoryCommandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskDevelopmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentCommandId");

                    b.HasIndex("TagDirectoryCommandId");

                    b.HasIndex("TaskDevelopmentId", "StartedAt");

                    b.HasIndex("TaskItemId", "StartedAt");

                    b.HasIndex(new[] { "Status" }, "IX_CommandExecutions_Active")
                        .HasFilter("\"Status\" IN (1, 2)");

                    b.ToTable("CommandExecutions", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Commands.DevelopmentCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("KeepTerminalOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresConfirmation")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TagDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("TagDirectoryId");

                    b.ToTable("DevelopmentCommands", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Commands.DevelopmentCommandParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DevelopmentCommandId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Options")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentCommandId", "Order");

                    b.ToTable("DevelopmentCommandParameters", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.AnonymizationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AnonymizationProfiles", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.AnonymizationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Argument")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Column")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfirmedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sensitivity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Schema", "Table", "Column")
                        .IsUnique();

                    b.ToTable("AnonymizationRules", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.AnonymizationSkippedTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfirmedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Schema", "Table")
                        .IsUnique();

                    b.ToTable("AnonymizationSkippedTables", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.DatabaseConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Database")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Environment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecretReference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SslMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoredPermissions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Permissions");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DatabaseConnections", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.DatabaseCopyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AnonymizationProfileId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DestinationConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSchema")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KeepAnonymizedArtifact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("RecreateDestination")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireAnonymization")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDatabase")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerifyAfterRestore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnonymizationProfileId");

                    b.HasIndex("DestinationConnectionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SourceConnectionId");

                    b.ToTable("DatabaseCopyProfiles", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.DatabaseOperationAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnonymizationProfile")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("AnonymousDumpSize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DestinationConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationConnectionName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationDatabase")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationDatabaseVersion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DumpSize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaskedColumnsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RowsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceConnectionName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDatabase")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDatabaseVersion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersions")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DatabaseOperationAudits_Running")
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("DatabaseOperationAudits", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.SavedDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(47)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid?>("AnonymizationProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("AnonymizationProfileId");

                    b.HasIndex("ConnectionId");

                    b.ToTable("SavedDatabases", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.StickyNotes.StickyNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ArchivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConvertedTaskId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Emphasis")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Opacity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaletteColor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<int?>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt")
                        .HasDatabaseName("IX_StickyNotes_Archived")
                        .HasFilter("\"ArchivedAt\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_StickyNotes_Trashed")
                        .HasFilter("\"DeletedAt\" IS NOT NULL");

                    b.HasIndex("TagId");

                    b.ToTable("StickyNotes", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tags.TagDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId", "Alias")
                        .IsUnique();

                    b.ToTable("TagDirectories", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tags.TagDirectoryCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandOverride")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DevelopmentCommandId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TagDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectoryOverride")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentCommandId");

                    b.HasIndex("TagDirectoryId", "DevelopmentCommandId")
                        .IsUnique();

                    b.HasIndex("TagDirectoryId", "Order");

                    b.ToTable("TagDirectoryCommands", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskDevelopment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentPrompt")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTag")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StatusChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskDevelopments", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskDevelopmentCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskDevelopmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskDevelopmentId", "Order");

                    b.ToTable("TaskDevelopmentCommands", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ArchivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ConcludedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeadlineAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Estimate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EstimateTicks");

                    b.Property<string>("NextAction")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt")
                        .HasDatabaseName("IX_Tasks_Archived")
                        .HasFilter("\"ArchivedAt\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.HasIndex("ConcludedAt")
                        .HasDatabaseName("IX_Tasks_ReadyToArchive")
                        .HasFilter("\"ConcludedAt\" IS NOT NULL AND \"ArchivedAt\" IS NULL AND \"DeletedAt\" IS NULL");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Tasks_Trashed")
                        .HasFilter("\"DeletedAt\" IS NOT NULL");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskItemTag", b =>
                {
                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TaskItemTags", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DeadlineDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Deadline_Date");

                    b.Property<TimeOnly?>("DeadlineTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("Deadline_Time");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("DeadlineDate")
                        .HasDatabaseName("IX_TaskOccurrences_Deadline")
                        .HasFilter("\"Deadline_Date\" IS NOT NULL AND \"Status\" = 0");

                    b.HasIndex("ScheduledDate", "Status");

                    b.HasIndex("TaskItemId", "ScheduledDate", "ScheduledTime")
                        .IsUnique();

                    b.ToTable("TaskOccurrences", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.TimeTracking.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskOccurrenceId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TaskOccurrenceId", "StartedAt");

                    b.ToTable("TimeEntries", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Infrastructure.Persistence.AgentAlertSoundRow", b =>
                {
                    b.Property<int>("Activity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoundId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Activity");

                    b.ToTable("AgentAlertSounds", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Infrastructure.Persistence.AgentSettingsRow", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Effort")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("MonitorActivity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProviderId");

                    b.ToTable("AgentSettings", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Infrastructure.Persistence.BranchSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conventions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BranchSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_BranchSettings_SingleRow", "Id = 1");
                        });
                });

            modelBuilder.Entity("MyTaskApp.Infrastructure.Persistence.DataRetentionSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoArchiveAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoArchiveEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrashRetentionDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DataRetentionSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_DataRetentionSettings_SingleRow", "Id = 1");
                        });
                });

            modelBuilder.Entity("MyTaskApp.Infrastructure.Persistence.DeadlineSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("DefaultTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OverdueRepeatEvery")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OverdueRepeatEveryTicks");

                    b.Property<int>("Stages")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeadlineSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeadlineSettings_SingleRow", "Id = 1");
                        });
                });

            modelBuilder.Entity("MyTaskApp.Infrastructure.Persistence.ReminderSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anchor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PausedUntilUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RepeatEvery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RepeatUntilAcknowledged")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReminderSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReminderSettings_SingleRow", "Id = 1");
                        });
                });

            modelBuilder.Entity("MyTaskApp.Domain.Agents.AgentSession", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Tasks.TaskDevelopment", null)
                        .WithMany()
                        .HasForeignKey("TaskDevelopmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyTaskApp.Domain.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Commands.CommandExecution", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Commands.DevelopmentCommand", null)
                        .WithMany()
                        .HasForeignKey("DevelopmentCommandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyTaskApp.Domain.Tags.TagDirectoryCommand", null)
                        .WithMany()
                        .HasForeignKey("TagDirectoryCommandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyTaskApp.Domain.Tasks.TaskDevelopment", null)
                        .WithMany()
                        .HasForeignKey("TaskDevelopmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyTaskApp.Domain.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Commands.DevelopmentCommand", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Tags.TagDirectory", null)
                        .WithMany()
                        .HasForeignKey("TagDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Commands.DevelopmentCommandParameter", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Commands.DevelopmentCommand", null)
                        .WithMany("Parameters")
                        .HasForeignKey("DevelopmentCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.AnonymizationProfile", b =>
                {
                    b.HasOne("MyTaskApp.Domain.DatabaseOperations.DatabaseConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.AnonymizationRule", b =>
                {
                    b.HasOne("MyTaskApp.Domain.DatabaseOperations.AnonymizationProfile", null)
                        .WithMany("Rules")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.AnonymizationSkippedTable", b =>
                {
                    b.HasOne("MyTaskApp.Domain.DatabaseOperations.AnonymizationProfile", null)
                        .WithMany("SkippedTables")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.DatabaseCopyProfile", b =>
                {
                    b.HasOne("MyTaskApp.Domain.DatabaseOperations.AnonymizationProfile", null)
                        .WithMany()
                        .HasForeignKey("AnonymizationProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyTaskApp.Domain.DatabaseOperations.DatabaseConnection", null)
                        .WithMany()
                        .HasForeignKey("DestinationConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyTaskApp.Domain.DatabaseOperations.DatabaseConnection", null)
                        .WithMany()
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.SavedDatabase", b =>
                {
                    b.HasOne("MyTaskApp.Domain.DatabaseOperations.AnonymizationProfile", null)
                        .WithMany()
                        .HasForeignKey("AnonymizationProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyTaskApp.Domain.DatabaseOperations.DatabaseConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.StickyNotes.StickyNote", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Tags.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tags.TagDirectory", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Tags.Tag", null)
                        .WithMany("Directories")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tags.TagDirectoryCommand", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Commands.DevelopmentCommand", null)
                        .WithMany()
                        .HasForeignKey("DevelopmentCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyTaskApp.Domain.Tags.TagDirectory", null)
                        .WithMany("Commands")
                        .HasForeignKey("TagDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskDevelopment", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Tasks.TaskItem", null)
                        .WithMany("Developments")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskDevelopmentCommand", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Tasks.TaskDevelopment", null)
                        .WithMany("Commands")
                        .HasForeignKey("TaskDevelopmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskItem", b =>
                {
                    b.OwnsOne("MyTaskApp.Domain.External.ExternalLink", "External", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("External_Id");

                            b1.Property<string>("IssueType")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("External_IssueType");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("External_Provider");

                            b1.Property<string>("Status")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("External_Status");

                            b1.Property<long>("SyncedAt")
                                .HasColumnType("INTEGER")
                                .HasColumnName("External_SyncedAt");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("External_Title");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("External_Url");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.OwnsOne("MyTaskApp.Domain.Reminders.ReminderPolicy", "Reminder", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Anchor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_Anchor");

                            b1.Property<int>("Channels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_Channels");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_IsEnabled");

                            b1.Property<long>("Offset")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_OffsetTicks");

                            b1.Property<long>("RepeatEvery")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_RepeatEveryTicks");

                            b1.Property<bool>("RepeatUntilAcknowledged")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_Repeat");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.Navigation("External");

                    b.Navigation("Reminder")
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskItemTag", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Tags.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyTaskApp.Domain.Tasks.TaskItem", null)
                        .WithMany("Tags")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskOccurrence", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Tasks.TaskItem", null)
                        .WithMany("Occurrences")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MyTaskApp.Domain.Deadlines.DeadlineAlertState", "DeadlineAlert", b1 =>
                        {
                            b1.Property<Guid>("TaskOccurrenceId")
                                .HasColumnType("TEXT");

                            b1.Property<long?>("LastAlertAtUtc")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DeadlineAlert_LastAlertAtUtc");

                            b1.Property<int>("LastStage")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DeadlineAlert_LastStage");

                            b1.Property<long?>("SnoozedUntilUtc")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DeadlineAlert_SnoozedUntilUtc");

                            b1.HasKey("TaskOccurrenceId");

                            b1.ToTable("TaskOccurrences");

                            b1.WithOwner()
                                .HasForeignKey("TaskOccurrenceId");
                        });

                    b.OwnsOne("MyTaskApp.Domain.Reminders.ReminderState", "Reminder", b1 =>
                        {
                            b1.Property<Guid>("TaskOccurrenceId")
                                .HasColumnType("TEXT");

                            b1.Property<long?>("AcknowledgedAtUtc")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_AcknowledgedAtUtc");

                            b1.Property<int?>("AcknowledgedBy")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_AcknowledgedBy");

                            b1.Property<int>("Attempt")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_Attempt");

                            b1.Property<long?>("LastFiredAtUtc")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_LastFiredAtUtc");

                            b1.Property<long?>("NextFireAtUtc")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_NextFireAtUtc");

                            b1.Property<long?>("WaitingSinceUtc")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_WaitingSinceUtc");

                            b1.HasKey("TaskOccurrenceId");

                            b1.HasIndex("NextFireAtUtc")
                                .HasFilter("\"Reminder_NextFireAtUtc\" IS NOT NULL AND \"Reminder_AcknowledgedAtUtc\" IS NULL");

                            b1.ToTable("TaskOccurrences");

                            b1.WithOwner()
                                .HasForeignKey("TaskOccurrenceId");
                        });

                    b.Navigation("DeadlineAlert")
                        .IsRequired();

                    b.Navigation("Reminder")
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.TimeTracking.TimeEntry", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Tasks.TaskOccurrence", null)
                        .WithMany()
                        .HasForeignKey("TaskOccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Commands.DevelopmentCommand", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("MyTaskApp.Domain.DatabaseOperations.AnonymizationProfile", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("SkippedTables");
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tags.Tag", b =>
                {
                    b.Navigation("Directories");
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tags.TagDirectory", b =>
                {
                    b.Navigation("Commands");
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskDevelopment", b =>
                {
                    b.Navigation("Commands");
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskItem", b =>
                {
                    b.Navigation("Developments");

                    b.Navigation("Occurrences");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
