// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTaskApp.Infrastructure.Persistence;

#nullable disable

namespace MyTaskApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MyTaskAppDbContext))]
    [Migration("20260919210955_Reminders")]
    partial class Reminders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("ScheduledDate", "Status");

                    b.HasIndex("TaskItemId", "ScheduledDate", "ScheduledTime")
                        .IsUnique();

                    b.ToTable("TaskOccurrences", (string)null);
                });

            modelBuilder.Entity("MyTaskApp.Infrastructure.Persistence.ReminderSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anchor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PausedUntilUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RepeatEvery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RepeatUntilAcknowledged")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReminderSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReminderSettings_SingleRow", "Id = 1");
                        });
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskItem", b =>
                {
                    b.OwnsOne("MyTaskApp.Domain.Reminders.ReminderPolicy", "Reminder", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Anchor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_Anchor");

                            b1.Property<int>("Channels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_Channels");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_IsEnabled");

                            b1.Property<long>("Offset")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_OffsetTicks");

                            b1.Property<long>("RepeatEvery")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_RepeatEveryTicks");

                            b1.Property<bool>("RepeatUntilAcknowledged")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_Repeat");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.Navigation("Reminder")
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskOccurrence", b =>
                {
                    b.HasOne("MyTaskApp.Domain.Tasks.TaskItem", null)
                        .WithMany("Occurrences")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MyTaskApp.Domain.Reminders.ReminderState", "Reminder", b1 =>
                        {
                            b1.Property<Guid>("TaskOccurrenceId")
                                .HasColumnType("TEXT");

                            b1.Property<long?>("AcknowledgedAtUtc")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_AcknowledgedAtUtc");

                            b1.Property<int?>("AcknowledgedBy")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_AcknowledgedBy");

                            b1.Property<int>("Attempt")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_Attempt");

                            b1.Property<long?>("LastFiredAtUtc")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_LastFiredAtUtc");

                            b1.Property<long?>("NextFireAtUtc")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_NextFireAtUtc");

                            b1.Property<long?>("WaitingSinceUtc")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Reminder_WaitingSinceUtc");

                            b1.HasKey("TaskOccurrenceId");

                            b1.HasIndex("NextFireAtUtc")
                                .HasFilter("\"Reminder_NextFireAtUtc\" IS NOT NULL AND \"Reminder_AcknowledgedAtUtc\" IS NULL");

                            b1.ToTable("TaskOccurrences");

                            b1.WithOwner()
                                .HasForeignKey("TaskOccurrenceId");
                        });

                    b.Navigation("Reminder")
                        .IsRequired();
                });

            modelBuilder.Entity("MyTaskApp.Domain.Tasks.TaskItem", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
